import { readdirSync, readFileSync, writeFileSync } from "node:fs";

// Keep the Sass catalogue aligned with the SVG filenames, without changing assets.
const directory = new URL("../src/styles/assets/feather/", import.meta.url);
const destination = new URL("../src/styles/_feather.scss", import.meta.url);
const names = readdirSync(directory)
  .filter((file) => file.endsWith(".svg"))
  .map((file) => file.slice(0, -4))
  .sort();
if (
  !names.length ||
  names.some((name) => !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name))
)
  throw new Error("Feather icons must have lowercase, hyphen-separated names.");
const source = [
  "// Generated by scripts/build-icons.mjs from assets/feather/*.svg. Do not edit.",
  "$feather-icons: (",
  ...names.map((name) => `  "${name}": url("./assets/feather/${name}.svg"),`),
  ");",
  "",
].join("\n");

if (process.argv.includes("--check")) {
  if (readFileSync(destination, "utf8") !== source)
    throw new Error(
      "Feather catalogue is out of date. Run bun run build:icons."
    );
} else {
  writeFileSync(destination, source);
  console.log(`Indexed ${names.length} Feather icons.`);
}
